pipeline {
    agent any

    environment {
        DJANGO_SETTINGS_MODULE = 'messaging_app.settings'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/ifedips20s-bit/alx-backend-python.git',
                    credentialsId: '4b618cbf-401a-4b9e-a9b7-e96e017252ec'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                 venv/bin/activate
                 pip3 install --upgrade pip'
              pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest messaging_app --junitxml=reports/results.xml'
            }
            post {
                always {
                    junit 'reports/results.xml'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
